### ISSUE TITLE
meta 4.8 update broke metacum for metacont object

### ISSUE THREAD

**Issue by felixthoemmes** [guido-s/meta#1]
In 4.7 the following minimal example worked, but in 4.8 report an error:

data(Fleiss93cont)
meta1 <- metacont(n.e, mean.e, sd.e, n.c, mean.c, sd.c, data=Fleiss93cont, sm="SMD")
meta1
forest(meta1)
metacum(meta1)

Thanks for creating the very useful meta package!

**Comment by guido-s** [comment]
Thank you for pointing out this bug. Fixed in meta, version 4.8-1.
I just added checks of metacum() and metainf() for all meta-analysis objects, i.e., metacor() - metarate(), to my test suite.
