### ISSUE TITLE
Can I run meta with only z-scores and p-values?

### ISSUE THREAD

**Issue by BinglanLi** [guido-s/meta#15]
Hello there,

I have been reading meta manual for the past few days, but could not get a clear answer. Is it possible to run meta with z-scores and p-values (sample sizes are available if needed)?

Thanks

**Comment by guido-s** [comment]
No, R package **meta** does not provide methods to combine z-scores or p-values. You could have a look at R package [**metap**](https://cran.r-project.org/package=metap).
