### ISSUE TITLE
Possibly bug in metabind

### ISSUE THREAD

**Issue by fmmattioni** [guido-s/meta#21]
I have noticed that `metabind` is checking whether the meta-analysis objects have the same arguments. Possibly here:

https://github.com/guido-s/meta/blob/492c5add580a3f24b8be3276c59b60df77a750b2/R/metabind.R#L495-L501

However, the problem is that arguments like `warn` do not influence the calculations and still are being considered in this check.

```
warn     A logical indicating whether warnings should be printed (e.g., if studies are excluded from meta-analysis due to zero standard deviations).
```

**reprex**:

``` r
library(meta)
#> Loading 'meta' package (version 4.11-1).
#> Type 'help(meta)' for a brief overview.

data(Fleiss93cont)

Fleiss93cont$age <- c(55, 65, 55, 65, 55)

Fleiss93cont$region <- c("Europe", "Europe", "Asia", "Asia", "Europe")

m1 <- metacont(n.e, mean.e, sd.e, n.c, mean.c, sd.c, data = Fleiss93cont, sm = "MD")

mu1 <- update(m1, byvar = age, bylab = "Age group", warn = TRUE)
mu2 <- update(m1, byvar = region, bylab = "Region", warn = FALSE)

metabind(mu1, mu2)
#> Error in metabind(mu1, mu2): All meta-analyses must use the same basic settings which differ for the following argument: 'warn'
```

<sup>Created on 2020-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Any thoughts on this?

**Comment by guido-s** [comment]
Thank you for pointing out this bug. I have removed the arguments _warn_ and _prediction_ from these checks.
