### ISSUE TITLE
Modifying the appearance of the 95%CI 

### ISSUE THREAD

**Issue by dtdibaba** [guido-s/meta#24]
Hi:
I had a question about the 95%CI appearance but the cilayout("(", ",  ") resolved it for me.
Thank you for the nice package.

**Comment by guido-s** [comment]
My answer would also have been to use `cilayout()`. 

Furthermore, you could use the following commands to print the risk ratio and its confidence interval in a single column (and use a different column label for RR + CI):
```
example(metabin)
forest(m1,
       rightcols = c("effect.ci", "w.fixed", "w.random"),
       rightlabs = c("Effect (95%-CI)", NA, NA))
```

**Comment by dtdibaba** [comment]
Great, thank very much!
Daniel
