### ISSUE TITLE
Calcalate hazard ratio using metabin function

### ISSUE THREAD

**Issue by t-r-uth** [guido-s/meta#25]
Hi, 

I have a set of binary/dichotomous outcomes. I wanted to calculate the hazard ratio for meta analysis and network meta analysis. However when I look at "meta" package "metabin"function "sm" argument, only risk ratio(RR) and odds ratio(OR) are available.

**Comment by guido-s** [comment]
The hazard ratio is a summary measure for time-to-event data, not binary data.

However, in a study without censoring the hazard ratio and risk ratio are (in principle) the same - if the observation times in the two groups are comparable.
