### ISSUE TITLE
forest(...,bysort=TRUE,...) mixes subgroup effects

### ISSUE THREAD

**Issue by eisber** [guido-s/meta#28]
I think I’m facing a bug when using forest(…, bysort=TRUE). The subgroup p-values don’t seem to match up anymore…

Version:  'meta' package (version 4.15-1).

bysort=FALSE
 
![image](https://user-images.githubusercontent.com/10142286/103552039-8d2f6600-4eab-11eb-9064-7cf049c5db60.png)

bysort=TRUE
 
![image](https://user-images.githubusercontent.com/10142286/103552052-90c2ed00-4eab-11eb-8738-54baa22c44ec.png)

Bysort=TRUE, the z=14.05 is now w/ a different group
 
![image](https://user-images.githubusercontent.com/10142286/103552059-93254700-4eab-11eb-81aa-40074b284f8e.png)

options(repr.plot.width=20, repr.plot.height=60, repr.plot.res = 200)

m.bin <- metacont(InterventionN,
                  IntensityofPainInterventionMean,
                  IntensityofPainInterventionSD,
                  ControlN,
                  IntensityofPainControlMean,
                  IntensityofPainControlSD,
                  data = data,
                  studlab = paste(str_pad(Study, max(sapply(Study, str_length)), 'right'), # Pad it
                                 str_pad(InterventionContinuousvsSingleshotvsLiposomalBupivacaine, max(sapply(InterventionContinuousvsSingleshotvsLiposomalBupivacaine, str_length)), 'right'),
                                 ComparatorControl, 
                                 sep=" | "),
                  comb.fixed = TRUE,
                  comb.random = FALSE,
                  byvar=paste(TypeofSurgery, outcome, ComparatorControlClean, sep=" | "),
                  hakn = TRUE,
                  prediction = TRUE)

pdf(file = 'Pain Comparison sort.pdf',  width=18, height=40)

forest(m.bin,
       sortvar=-Year, #paste(ComparatorControl, InterventionContinuousvsSingleshotvsLiposomalBupivacaine, Study),
       bysort=TRUE,
       fontfamily="mono",
       lab.e = "Intervention",
       pooled.totals = TRUE,
       pooled.events = TRUE,
       overall = TRUE,
       bylab = "", # Label before the subgroup
       print.tau2 = FALSE,
       col.diamond = "blue",
       col.diamond.lines = "black",
       col.predict = "black",
       print.I2.ci = TRUE,
       digits.sd = 2,
       test.overall = TRUE,
       test.subgroup = TRUE,
       print.stat = TRUE,
       test.effect.subgroup = TRUE
)

dev.off()

**Comment by guido-s** [comment]
Thank you for reporting this bug (which should be fixed now).
