### ISSUE TITLE
Missing R^2 value in meta regression using function "metareg"

### ISSUE THREAD

**Issue by exingwjx** [guido-s/meta#31]
Hi, 
this is Jiaxing Wang from Emory university, US.
I am using R package "meta" for a meta-analysis.
However, when applying the "metareg" function for meta-regression, it does not report R2 (the amount of heterogeneity explained by each variable). It only reports Tau^2, Tau, I^2 and H^2 .

**My question is: how to get the R^2 value?**

My session info:
- R version 3.6.3 (2020-02-29)
- Platform: x86_64-w64-mingw32/x64 (64-bit)
- Running under: Windows 10 x64 (build 18363)
- Package "meta":  meta_4.18-0

Jiaxing

**Comment by guido-s** [comment]
I guess that you model does not contain an intercept. In such cases R2 is not reported (see help page of print.rma.uni).

**Comment by guido-s** [comment]
Another explanation could be that a generalized linear mixed model was used which does not return R2 (see help page of rma.glmm called internally).
