### ISSUE TITLE
Metabind function showing error

### ISSUE THREAD

**Issue by pavanaditya369** [guido-s/meta#32]
Respected sir
The metabind function I am using for plotting a forest plot for comparison between the subgroups is showing an error
#code below
db1 <- db0[ which(db0$Pollutant=='PM10' & db0$Measure=='AVERAGE' & db0$Outcome=='Total Mortality' & db0$Age=='All' & db0$Sex=='All' & (db0$Lag=='0-1' ))
db1$LnEE.spm.unadjusted <- as.numeric(db1$LnEE.spm.unadjusted)
db1$SELnEE.spm.unadjusted <- as.numeric(db1$SELnEE.spm.unadjusted)
model <- metagen(TE=db1$LnEE.spm.unadjusted, seTE=db1$SELnEE.spm.unadjusted, studlab=db1$Article, sm="RR", comb.random=TRUE, method.tau="DL", hakn=FALSE, backtransf=TRUE, prediction=TRUE, level.predict=0.80)
summary(model)

# --- Forest plot for the contrast between subgroups

mu1 <- update(model, byvar = db1$Lag)
mb1 <- metabind(mu1)
mb1
forest(mb1)
On running this, the error is showing up as
"Error in metabind(mu1) : object 'args2' not found"
Previously the results were  coming but now, they error pops up
Kindly help

**Comment by guido-s** [comment]
Thank you for pointing out this bug.
