### ISSUE TITLE
could you please add an model choose parameter

### ISSUE THREAD

**Issue by tcmzhou** [guido-s/meta#34]
Dear Dr. Guido Schwarzer

I am a researcher at Jinan University(Guangzhou, China). 

Recently, I have done a meta-analysis using the meta-package. I found it was very powerful and convenient except when I choose the model( random, fixed, or combined) to use.
Each time I choose the model parameter, I have to set “comb.fixed = TRUE, comb.random = FALSE” .
If there is a model parameter to set, it will make a big difference.

Thanks for your time. Have a nice day.

**Comment by guido-s** [comment]
Hi tcmzhou,

The R function `settings.meta()` can be used to define default settings for R package **meta** for the current R session.

E.g.,
- `settings.meta(comb.fixed = TRUE, comb.random = FALSE)` to only report results for the fixed effect model
- `settings.meta(hakn = TRUE)` to use the Hartung-Knapp method under the random effects model
- `settings.meta(method.tau = "PM")` to use the Paule-Mandel estimator for the between-study variance

In addition to single arguments, you can specify default settings, for example, to mimic the behaviour of RevMan 5 or to follow the recommendations of the JAMA journals (see `help(settings.meta)`).

Best
Guido

**Comment by tcmzhou** [comment]
Thanks very much.
