### ISSUE TITLE
What do the values saved in $TE.fixed reflect?

### ISSUE THREAD

**Issue by stefanleach** [guido-s/meta#36]
Hi there,

I wonder if you could help me understand some potential discrepancies in the output of the `metacor` function. I've attached a small dataset here in the hopes you can replicate my results. Here is the basic code I'm running, using the tidyverse and meta packages on the attached .csv file: [test.zip](https://github.com/guido-s/meta/files/6420786/test.zip).

```
test_data <- 
    read.csv("test.csv")
  
test_metacor <- 
    test_data %>%
    group_by(group) %>%
    summarize(cor = cor(v1, v2, use = "pairwise.complete.obs"),
              n = length(v1)) %>%
    metacor(cor,
            n,
            studlab = group,
            data=.)
  
test_metacor 
  
test_metacor$TE.fixed
```

I'm attempting to understand why I'm seeing different coefficients when accessing the results by calling `test_metacor` as opposed to `test_metacor$TE.fixed`. 

For example, when I call `test_metacor` I get:
```
                      COR    95%-CI           z      p-value
Fixed effect model    0.5691 [0.5108; 0.6221] 15.39  < 0.0001
Random effects model  0.5691 [0.3929; 0.7050]  5.48  < 0.0001
```

However, when i call `test_metacor$TE.fixed` I get:
```
0.6461636
```
I was under the impression, from using the other functions in the meta package (e.g., metamean), that `$TE.fixed` accessed the fixed effect estimate but maybe I'm wrong? Based on the results I see from accessing `test_metacor` I would have thought `test_metacor$TE.fixed` should give me `0.5691`. 

Any help would be appreciated.

Cheers,

Stefan

**Comment by guido-s** [comment]
Dear Stefan,

By default, a meta-analysis of correlations uses Fisher's z transformed correlations (see output of `gs("smcor")`) which are back-transformed in printouts.
Accordingly, list element 'TE.fixed' contains a z transformed correlation.

You can use the command `meta:::z2cor(0.6461636)` for the back-transformation.

Best,
Guido

**Comment by stefanleach** [comment]
Hi Guido,

Thanks so much for your speedy reply. That's super helpful.

Cheers,

Stefan
