### ISSUE TITLE
Heterogeneity stats overlapping with forest plot

### ISSUE THREAD

**Issue by rafanmir** [guido-s/meta#39]
Hi, I'm doing a forest plot of correlations, and since I only have 2 columns on the left the heterogeneity stats are overlapping with the x axis of the graph. I couldn't find anything in the help file about how can we move the hetstat line in the graph, the only solution I found was increasing colgap of the left columns but it created a lot of white space. Is there any other way to deal with this issue?
Thanks

**Comment by guido-s** [comment]
I added a new argument _addrows.below.overall_ to add empty rows below the meta-analysis results.

```
library(meta)

m <- metacor((1:5) / 6, rep(100, 5))

forest(m, text.fixed = "FE model", text.random = "RE model")

forest(m, text.fixed = "FE model", text.random = "RE model", addrows = 2)

forest(m, text.fixed = "FE model", text.random = "RE model",
       label.left = "A", label.right = "B")

forest(m, text.fixed = "FE model", text.random = "RE model",
       label.left = "A", label.right = "B",
       addrows = 3)
```
