### ISSUE TITLE
Tau-squared estimate for random effects model in metabin()

### ISSUE THREAD

**Issue by ymzhang-neo** [guido-s/meta#4]
Hi Guido,

I am new to meta-analysis and your package has been of great help! 

Pardon me for creating this issue about the code as well as the understanding of the DerSimonian-Laird method for the random effects model in the analysis of binary data.

Consider the following illustrative code: 
```
data(Olkin95)

meta1 <- metabin(event.e, n.e, event.c, n.c, data = Olkin95, method = "Inverse")
meta2 <- metabin(event.e, n.e, event.c, n.c, data = Olkin95, method = "MH")

meta1$Q; meta2$Q
meta1$tau; meta2$tau
```
The Q statistics of heterogeneity are different because the methods for the fixed effect model are different.  The DerSimonian-Laird estimates of tau-squared are also different.

I imagine this is because the respective Q statistic from the fixed effect method is directly used in the tau-squared estimation.  However, in the original paper by DerSimonian and Laird (1986), they suggested using Q from the inverse-variance method.  In two other reference (Normand 1999; Borenstein, Hedges, Higgins, and Rothstein 2009), the Q from the inverse-variance method was the only option. 

Could you provide some clarification about your choice (with possibly some references)?  My apologies for any misunderstanding.  Thank you for consideration!

References:
- Borenstein, M. , Hedges, L. V., Higgins, J. P. and Rothstein, H. R. _Introduction to Meta-Analysis_. Chichester, U.K: John Wiley & Sons (2009).
- DerSimonian R. and Laird N. Meta-analysis in clinical trials. _Controlled Clinical Trials_, 7(3), 177-188 (1986).
- Normand, S. T. Meta‐analysis: formulating, evaluating, combining, and reporting. _Statistics in Medicine_, 18, 321-359 (1999).

**Comment by guido-s** [comment]
Dear ymzhang-neo,

R function metabin() calculates the Q statistic for heterogeneity (and thus the DerSimonian-Laird estimate of between-study variance) like RevMan 5.3 (http://community.cochrane.org/help/tools-and-software/revman-5), the software used for preparing and maintaining Cochrane Reviews.

You can find the respective formulae in the manuscript
Statistical algorithms in Review Manager 5
Jonathan J Deeks and Julian PT Higgins
on behalf of the Statistical Methods Group of The Cochrane Collaboration
August 2010
which is available in RevMan 5.3 (menu: Help - Statistical Algorithms in RevMan).

At the moment, this information is not available in the help page of metabin(), however, I will add it with the next update of **meta** on CRAN.

Best wishes,
Guido
