### ISSUE TITLE
Atomic vector error when using id and byvar together

### ISSUE THREAD

**Issue by andrewpulford** [guido-s/meta#40]
Hi, I am getting the following error in certain conditions when using the `metagen` command to run a three-level meta-analysis (`id`) with sub-groups (`byvar`):

`Error: $ operator is invalid for atomic vectors`

It appears to be distinct from issue #38 and seems to occur specifically when one sub-group includes multiple data points from one study using a single reference group.  I have produced a minimum reproducible example below that behaves in the same manner as my own data.  Plain (2019) appears to be the study that causes the error when both `id` and `byvar` are passed.  Removing `byvar` allows the three-level meta-analysis to run successfully.  Sub-setting the data to exclude Plain (2019) also allows a nested three-level meta-analysis to run.

I would be grateful for any thoughts on how to resolve this issue.

Regards

Andy

Minimum reproducible example:

    library(meta)
    
    df <- data.frame(study = c("Brown 2011, exposed, males", 
                           "Brown 2011, exposed, females",
                           "Grant 2014, exposed, both sexes",
                           "Young 2012, medium exposed, both sexes",
                           "Young 2012, high exposed, both sexes",
                           "Plain 2019, medium exposed/medium dose, both sexes",
                           "Plain 2019, medium exposed/high dose, both sexes",
                           "Plain 2019, high exposed/medium dose, both sexes",
                           "Plain 2019, high exposed/high dose, both sexes"),
                 ref_group = c("Brown 2011, unexposed, males",
                               "Brown 2011, unexposed, males",
                               "Grant 2014, unexposed, both sexes",
                               "Young 2012, unexposed, both sexes",
                               "Young 2012, unexposed, both sexes",
                               "Plain 2019, unexposed, both sexes",
                               "Plain 2019, unexposed, both sexes",
                               "Plain 2019, unexposed, both sexes",
                               "Plain 2019, unexposed, both sexes"),
                 te = c(0.63, 0.77, 1.08, 1.23, 1.25,0.66, 0.78, 0.87, 0.93),
                 se = c(0.24, 0.16, 0.34, 0.28, 0.27,0.13, 0.18, 0.12, 0.17),
                 exposure_topic = c("A","A","B","B","B","C","C","C","C"))`

    ma <- metagen(TE = te, seTE = se, sm = paste("OR"), 
                  studlab = paste(study), 
                  data = df,
                  subgroup = exposure_topic, 
                  subgroup.name = "Exposure topic",
                  id = ref_group,
                  fixed = FALSE, random = TRUE)

[Link to repo](https://github.com/andrewpulford/min_reprex/blob/main/meta_three-level_reprex.R) (includes un-nested version and subset excluding Plain (2019))

**Comment by guido-s** [comment]
Andrew,

Thank you for pointing out this bug in `metagen()`.

Actually, the bug is not related to subgroup analysis but having a (sub)group of estimates all coming from a single study.

The following R command generated the same error message:

```
metagen(TE = te, seTE = se, studlab = study, id = ref_group,
  data = df, sm = "OR",
  subset = ref_group == "Plain 2019, unexposed, both sexes")

```
Best, Guido

**Comment by andrewpulford** [comment]
Hi Guido

Thanks for getting back to me on this.  I'd wondered if it was a function of the grouped meta-analysis rather than a package bug, so thanks for clarifying.  I think the solution is to present the three-level meta-analysis without sub-groups and include separate forest plots for sub-groups in a supplementary document.

Regards

Andy
