### ISSUE TITLE
Metacont doesn't calculate SMD if the number of participants is high

### ISSUE THREAD

**Issue by lizatymchenko** [guido-s/meta#44]
Hi, 

I have a weird issue with the data analysis while I use **metacont** from package Meta. 
Some of my studies have a high number of participants and for these studies, metacont doesn't calculate SMD. 
I tried to find out why that is the case but I cannot find an explanation or a solution. 
When I figured out that the n.e and n.c is the problem I tried to change them to see what will happen, the SMD is calculated. 

Does someone know how to solve this issue?

> library(dmetar)
> library(esc)
> library(tidyverse)
> library(meta)

> meta_function <- read_excel("meta_function.xlsx")
> str(meta_function)
tibble [25 x 7] (S3: tbl_df/tbl/data.frame)
 $ author : chr [1:25] "Bennell 2018" "Peters 2017" "Irvine 2015" "Calner 2017" ...
 $ n.e    : num [1:25] 73 226 199 55 101 6 16 17 44 54 ...
 $ n.c    : num [1:25] 71 50 398 44 61 8 16 15 49 54 ...
 $ smd_int: num [1:25] 0.337 0.23 0.286 0.305 1.23 ...
 $ sd_int : num [1:25] 129.46 8.47 1.05 17.73 21.57 ...
 $ smd_con: num [1:25] 0.366 0.103 0.149 0.128 0.207 ...
 $ sd_con : num [1:25] 109.93 7.93 1.08 18.78 21.37 ...

> m.cont <- metacont(n.e = n.e,
+                    mean.e = smd_int,
+                    sd.e = sd_int,
+                    n.c = n.c,
+                    mean.c = smd_con,
+                    sd.c = sd_con,
+                    studlab = author,
+                    data = meta_function,
+                    sm = "SMD",
+                    method.smd = "Hedges",
+                    fixed = FALSE,
+                    random = TRUE,
+                    method.tau = "REML",
+                    hakn = TRUE,
+                    title = "meta analysis")
> summary(m.cont)
Review:     meta analysis

                         SMD            95%-CI %W(random)
Bennell 2018         -0.0002 [-0.3269; 0.3265]        6.2
Peters 2017           0.0151 [-0.2912; 0.3214]        7.0
Irvine 2015               NA                          0.0
Calner 2017           0.0096 [-0.3868; 0.4061]        4.2
Mecklenburg 2018      0.0474 [-0.2705; 0.3652]        6.5
Johnston 2010         0.0484 [-1.0103; 1.1071]        0.6
Blixen 2004          -0.0200 [-0.7130; 0.6729]        1.4
Ang 2010              0.0161 [-0.6782; 0.7104]        1.4
Shigaki 2013          0.0219 [-0.3852; 0.4290]        4.0
Petrozzi 2019         0.0602 [-0.3171; 0.4375]        4.6
Shebib 2019           0.0267 [-0.2799; 0.3334]        7.0
Toelle 2019           0.0067 [-0.4161; 0.4295]        3.7
Chiauzzi 2010        -0.1712 [-0.4499; 0.1075]        8.5
Williams 2010         0.0036 [-0.3572; 0.3645]        5.1
Carpenter 2012        0.1137 [-0.2167; 0.4441]        6.0
Dear 2013                 NA                          0.0
Pozo-Cruz 2012a       0.0676 [-0.3458; 0.4810]        3.9
Kristjansdottir 2013  0.0097 [-0.3278; 0.3471]        5.8
Amorim 2019           0.0128 [-0.4626; 0.4881]        2.9
Piqueras 2013        -0.0004 [-0.3294; 0.3286]        6.1
Bini 2017            -0.0472 [-0.7900; 0.6957]        1.2
Russell 2011          0.0102 [-0.4765; 0.4970]        2.8
Li 2014              -0.0444 [-0.3022; 0.2134]        9.9
Iles 2011             0.0373 [-0.6784; 0.7531]        1.3
Lorig 2002                NA                          0.0

Number of studies combined: k = 22
Number of observations: o = 3965

                        SMD            95%-CI    t p-value
Random effects model 0.0024 [-0.0268; 0.0315] 0.17  0.8667

Quantifying heterogeneity:
 tau^2 = 0; tau = 0; I^2 = 0.0% [0.0%; 46.2%]; H = 1.00 [1.00; 1.36]

Test of heterogeneity:
    Q d.f. p-value
 2.40   21  1.0000

Details on meta-analytical method:
- Inverse variance method
- Restricted maximum-likelihood estimator for tau^2
- Hartung-Knapp adjustment for random effects model
- Hedges' g (bias corrected standardised mean difference; using exact formulae)

**Comment by guido-s** [comment]
I assume this was related to https://github.com/guido-s/meta/issues/42 .
