### ISSUE TITLE
Aesthetics: remove overall effect estimate ref line and add line at top of pot

### ISSUE THREAD

**Issue by mgirdwood7** [guido-s/meta#46]
Hi there, 

Thank you for the ```meta``` package, it is very useful and the customisation of plots is fantastic. 

These two points are barely 'issues' and really just very small customisations to the ```forest.meta``` plot if you could help.

1. I was wanting to remove the dotted ref line for the estimate of effect in the plot - is there anyway to do this? I was digging through the source code but couldn't find an immediate easy option unless I missed something? The ```ref``` parameter is only for the solid reference line right?

2. Is there anyway to add a solid line across the top of the plot (i.e. extending from the left col to the right col at top of y axis (ymax?) but under the column headings? Again I was playing around with modifying the source code but couldn't get a line to sit permanently in position without the position of it moving based on plot size. Out of curiosity how do you get the plots to sit in a "fixed" position regardless of the window/plot sizing?

As I mentioned these are really not 'problems', more aesthetic modifications, so if no easy solution of course that's fine :)

**Comment by mgirdwood7** [comment]
Well i found a work around to my first mini problem for anyone interested - specifying ```col.random = "white"``` effectively 'hid' the line.

**Comment by guido-s** [comment]
It took me some time to look into this, however, the issue should be fixed with the new argument 'header.line'.

I would use `col.random = "transparent"` to remove the random effects line. But the colour white works also.

**Comment by mgirdwood7** [comment]
Amazing thank you!
