### ISSUE TITLE
meta.forest; subgroup effect

### ISSUE THREAD

**Issue by fohofmann** [guido-s/meta#49]
Hi Guido, hi everyone,

thank you for your help and the solution regarding the last issue (#48), and I am really sorry to bother you once again.

Given the previously explored example
``` R
# libraries
library(meta)
library(data.table)

# data
dt <- data.table(
 ID = rep(1:5, each=3),
 AE = rep(c("minor","major","deadly"),5),
 ni = rep(c(25,19,101,32,50), each=3),
 xi = c(2,3,3,4,1,0,29,13,4,7,4,1,7,2,1) )

# meta-analysis & forest plot
res <- metaprop(xi, ni, cluster=ID, subgroup=AE, data=dt)
forest(res, subgroup=T)
```

`metaprop()` works fine, and also estimates of the effect are reported.
However, `forest()` does not plot the summary effect per subgroup, regardless how the arguments `type.random`, `type.subgroup`or `type.subgroup.random` are defined.

Any advices? Wrong configuration at my side, or a structural problem of `forest()`?
Sorry once again, and all the best,
Felix

**Comment by guido-s** [comment]
Felix,

It took me some time to look into this. Should be fixed now.

Best wishes,
Guido

**Comment by fohofmann** [comment]
Thank you again for all your efforts, Guido!

> Error in runMLM(c(list.mlm, list(data = data.frame(cluster = cluster[sel.4],  : could not find function "runMLM"
> Calls: <Anonymous> ... eval_with_user_handlers -> eval -> eval -> metaprop -> metagen

As far as I understand `extrMLM`and `runMLM`are wrapper-functions to pass over mlm-arguments to metafor:rma.mv.
I would have expected their definition in `meta-aux.R`(comparable to `runNN`, but with preset func-arg or sth similar)?

**Comment by guido-s** [comment]
Classic mistake - I had the auxiliary functions in other files which I did not upload to the Git repository. I added them to `meta-aux.R` as suggested by you.

**Comment by fohofmann** [comment]
Thanks for getting back on this. Works perfectly fine now. Thank you!
