### ISSUE TITLE
Print p-values in forest from metainf

### ISSUE THREAD

**Issue by fmmattioni** [guido-s/meta#5]
Dear Prof. Schwarzer,

Thank you very much for this great package. I would like to know how I could print the **p-values** in a **forest** plot from **metainf**.

If I print the metainf results I get  **MD**, **95%-CI**, **p-value**, **tau^2**, and **I^2**. However, if I use a forest plot to visualize the results I only get **MD** and **95%-CI**.

Thank you.

**Comment by guido-s** [comment]
Dear Felipe,

This feature is not implemented in the forest function (at the moment). However, you can use the attached R code as a work around.

Best wishes,
Guido
[forest-metainf01.txt](https://github.com/guido-s/meta/files/2184877/forest-metainf01.txt)

**Comment by fmmattioni** [comment]
This is great!

Thank you for the code. Very much appreciated!

Best,

Felipe

**Comment by fmmattioni** [comment]
Just a quick question I have been struggling with:

Is there a way to get these additional columns (p-value, tau^2, and I^2) for the overall effect at the bottom of the forest plot? Example:

![forest-metainf01](https://user-images.githubusercontent.com/36630619/42599069-6719a156-855e-11e8-833a-addfd3af8090.png)

Thank you!

Felipe

**Comment by guido-s** [comment]
This is not possible at the moment. I will put this on my TODO list.

**Comment by fmmattioni** [comment]
Thanks for the feedback!

I thought it would be useful to compare the LOOCV results to the overall effect in a single place like this. Thank you again for this great package!

Best,

Felipe

**Comment by guido-s** [comment]
I finally had time to implement this feature.

**Comment by andygxzeng** [comment]
Thanks so much for implementing this - would it be possible to have this option for visualizing the results of metagen as well? I'm specifically interested in displaying the overall P-value for the fixed or random effects model

Best, 
Andy

**Comment by guido-s** [comment]
You can print the p-value of the test for overall effect using argument 'test.overall', 'test.overall.fixed' and 'test.overall.random'.

Or would you like to add a column with p-values for individual studies as well as meta-analysis results?

**Comment by guido-s** [comment]
Hi Andy,

I changed forest.meta() accordingly.

E.g.,
`forest(metagen(-2:2, 1:5 / 5, sm = "MD"), leftcols = FALSE, rightcols = c("effect", "ci", "pval"))`

Best,
Guido
