### ISSUE TITLE
Add more than 2 vertical lines to forest plot

### ISSUE THREAD

**Issue by florianteichert** [guido-s/meta#50]
Hi,
is it possible to include more than 2 lines in a forest plot? So far I only found out to edit 2 using the limits of equivalence argument (**lower/upper.equi**). However I would like to add **3 lines to both sides** indicating thresholds for small, moderate and large effects like in the image below (from the fully contextualised GRADE approach).

Best regards,
Florian

<img width="921" alt="Screenshot 2023-03-22 at 00 31 23" src="https://user-images.githubusercontent.com/115418816/226766695-74a2fafc-12cc-4d67-9a82-7cc71bda2855.png">

**Comment by guido-s** [comment]
Arguments `lower.equi` and `upper.equi` can be numeric vectors specifying the thresholds. Furthermore, the new arguments `fill.lower.equi` and `fill.upper.equi` can be used to specify the colours of the various regions. If the number of colours is equal to the number of thresholds plus 1, the region between the lowest / highest threshold and the minimun / maximum is also filled (see help page of `forest.meta` for an example).

**Comment by florianteichert** [comment]
Vielen Dank!
<img width="389" alt="Screenshot 2023-04-03 at 22 51 21" src="https://user-images.githubusercontent.com/115418816/229624904-addcc380-a097-47fd-9b28-0bad9ae7c542.png">
