### ISSUE TITLE
Function to extract effect size estimates from fitted objects

### ISSUE THREAD

**Issue by sfg** [guido-s/meta#53]
## Classification of issue
  - [X] feature request
  - [ ] bug report
  - [ ] support request (please do **not submit support requests here**, but use [R-sig-meta-analysis](https://stat.ethz.ch/mailman/listinfo/r-sig-meta-analysis))

## Summary
A function which cam extract the table with effect-size estimates from fitted meta-regression objects, e.g.:

 ```r
m1 <- metaprop(4:1, 10 * 1:4)
summary(m1)
  proportion           95%-CI
1     0.4000 [0.1216; 0.7376]
2     0.1500 [0.0321; 0.3789]
3     0.0667 [0.0082; 0.2207]
4     0.0250 [0.0006; 0.1316]
...
# output truncated
```
Or is there a convenient way to extract the table with proportions and CI from the object?

Regards, Sven

**Comment by guido-s** [comment]
Sven,

I added new functions extract() and extract.meta(), see https://github.com/guido-s/meta/blob/develop/R/extract.R or help(extract.meta) after installing the current development version of **meta**.

Best,
Guido
