### ISSUE TITLE
How to edit text in forest plot

### ISSUE THREAD

**Issue by 42kuroniko** [guido-s/meta#55]
![95ci](https://github.com/guido-s/meta/assets/136058430/a70f36df-2911-4659-aa68-c3339cbe8254)

Hi, developers, I want to know is there any parameters for me to change the text in the 95ci col. I would like to make the "[low; high]"  change to the "(low; high)". Please tell me what should i do for the editing.

**Comment by guido-s** [comment]
You can change the behaviour with the command `cilayout("(")`. See the help page of `cilayout()` for more details.

**Comment by 42kuroniko** [comment]
> You can change the behaviour with the command `cilayout("(")`. See the help page of `cilayout()` for more details.
ty, it really helps.
