### ISSUE TITLE
Issue with forest.meta

### ISSUE THREAD

**Issue by emjnixon15** [guido-s/meta#59]
Note: for support questions on R package **meta**, please use the [R-sig-meta-analysis mailing list](https://stat.ethz.ch/mailman/listinfo/r-sig-meta-analysis). This repository's issues are reserved for feature requests and bug reports.

## Classification of issue

Please indicate whether you want to submit a

  - [ ] feature request
  - [x ] bug report
  - [ ] support request (please do **not submit support requests here**, but use [R-sig-meta-analysis](https://stat.ethz.ch/mailman/listinfo/r-sig-meta-analysis))

## Summary

I have made tutorials and assignments for students which use the forest.meta() function in this package. However, code that has been working for months has suddenly stopped working the last few days with this error:

Error in `forest.meta()`:
! could not find function "forest.meta"
Execution halted

Even though I haven't changed anything.

I have tested this on multiple machines and get the same error. 

### Environment

I am using macOS
meta 7.0.0
R version 4.3.3

**Comment by guido-s** [comment]
As a general rule, generic functions like `forest.meta()` should not be called directly but via `forest()`. Accordingly, I made `forest.meta()` an internal function in **meta**, version 7.0-0.

It is still possible to directly access `forest.meta()` using the ":::" operator, i.e., `meta:::forest.meta()`. However, I would always rely on `forest()`.
