### ISSUE TITLE
Bubble plot not working

### ISSUE THREAD

**Issue by fmmattioni** [guido-s/meta#6]
Dear Prof. Schwarzer,

I am currently having problems when trying to produce a bubble plot from a meta regression.

I get the following error:

Error in stripchart.default(x1, ...) : invalid plotting method

I have just invited you to join my private repo in case you would like to reproduce the error.

Thank you,

Felipe

-------
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] meta_4.9-3

loaded via a namespace (and not attached):
[1] compiler_3.4.4 tools_3.4.4    yaml_2.2.0     grid_3.4.4

**Comment by fmmattioni** [comment]
I have just re-run it, and it is working now. I am sorry, I am not sure what happened.

Thank you,

Felipe

**Comment by fmmattioni** [comment]
OK, I figure out the problem. This happens when tidyverse is loaded.

**Comment by fmmattioni** [comment]
OK, I got it. I had my data as a tibble, and not as a data frame.

**Comment by guido-s** [comment]
Thank you for pointing out this bug. R function bubble.metareg() should work with tibbles instead of data frames.
I just fixed this bug (see https://github.com/guido-s/meta/commit/fee73439d99d83c5a75be3592091c5428a6fd5a5).

**Comment by fmmattioni** [comment]
This is great! Thank you very much!
