### ISSUE TITLE
Request to Incorporate Subgroups in Funnel Plots

### ISSUE THREAD

**Issue by nelsoncarvasjr** [guido-s/meta#62]
Dear Professor Schawazer,

I hope this message finds you well.

First and foremost, I would like to congratulate you on the excellent work you are doing with your repository. The tool has been extremely helpful for my analyses and for the research community.

I am writing to suggest an improvement that could make funnel plots even more versatile. Would it be possible to incorporate the functionality to visualize different subgroups within the same funnel plot? This feature would facilitate visual comparisons between subgroups and could enrich the analyses performed by users.

Thank you in advance for considering this suggestion and for your dedication to this project. I look forward to seeing how the repository continues to evolve.

Best regards,

**Comment by guido-s** [comment]
I change the use of arguments 'pch', 'cex', 'col', 'bg', 'text', and 'cex.studlab'.

The following R code can be used to show subgroup information in a funnel plot.

```
data(Fleiss1993cont)
Fleiss1993cont$region <- c("Europe", "Europe", "Asia", "Asia", "Europe")
m1 <- metacont(n.psyc, mean.psyc, sd.psyc, n.cont, mean.cont, sd.cont,
  data = Fleiss1993cont, sm = "SMD", studlab = paste(study, year),
  subgroup = region)
funnel(m1, col = setvals(subgroup), cex = 2, pch = 20)
funnel(m1, col = setvals(subgroup, c("green", "red")), cex = 2, pch = 20)
funnel(m1,
  col = setvals(subgroup, c("green", "red")),
  bg = setvals(subgroup, c("yellow", "blue")),
  cex = setvals(subgroup, c(6, 4)),
  pch = 20 + setvals(subgroup))
```

**Comment by nelsoncarvasjr** [comment]
Dear Professor Guido,

Thank you very much for sharing the code and the updates regarding the use of the 'pch', 'cex', 'col', 'bg', 'text', and 'cex.studlab' arguments. I found the approach to displaying subgroup information in the funnel plot very useful.

However, I encountered some issues when trying to run the setvals() function. Could you please clarify if this function will be part of a new update, or if there’s a specific package I need to install to use it correctly?

Thank you again for your assistance!

Best regards,

Nelson


> Em 16 de out. de 2024, à(s) 13:01, Guido Schwarzer ***@***.***> escreveu:
> 
> I change the use of arguments 'pch', 'cex', 'col', 'bg', 'text', and 'cex.studlab'.
> 
> The following R code can be used to show subgroup information in a funnel plot.
> 
> data(Fleiss1993cont)
> Fleiss1993cont$region <- c("Europe", "Europe", "Asia", "Asia", "Europe")
> m1 <- metacont(n.psyc, mean.psyc, sd.psyc, n.cont, mean.cont, sd.cont,
>   data = Fleiss1993cont, sm = "SMD", studlab = paste(study, year),
>   subgroup = region)
> funnel(m1, col = setvals(subgroup), cex = 2, pch = 20)
> funnel(m1, col = setvals(subgroup, c("green", "red")), cex = 2, pch = 20)
> funnel(m1,
>   col = setvals(subgroup, c("green", "red")),
>   bg = setvals(subgroup, c("yellow", "blue")),
>   cex = setvals(subgroup, c(6, 4)),
>   pch = 20 + setvals(subgroup))

**Comment by guido-s** [comment]
I wrote this auxiliary function to generate a vector with colors, point sizes etc. It is part of the GitHub version of R package **meta**.

For a factor variable, the levels are replaced by the values provided in argument 'vals'. For other variables, the sorted unique values are replaced by the values provided in argument 'vals'. Finally, either a numeric vector is returned if the input to argument 'vals' is numeric or a character vector is returned.

Could you provide an example highlighting the issues with _setvals()_?
