### ISSUE TITLE
Displaying mean and deviation (SD) in one column in metacont()/forest() functions 

### ISSUE THREAD

**Issue by wptmdoorn** [guido-s/meta#7]
Hi,

I have been looking through the API and internet for some hours now but I feel like I cannot find any satisfying answers. When we construct forest plots for a continuous measure (e.g. group mean) we use the metacont() -> forest() workflow. This will result (with correct alterations) in three columns showing the group size ('Total'), mean and SD for the control as well as experimental groups. 

I was wondering: is it possible to put the mean and SD into one column representing it as; mean (± SD) such as 28.0 (± 1.2)? 

Thank you for the help.

**Comment by guido-s** [comment]
I would do this the following way:

1. Add a column with the (already formated) information to the dataset
2. In forest.meta(), use argument 'leftcols' to add new columns to the forest plot (and argument 'leftlabs' to provide a label.

Please have a look at the R code for an example: [forest14.txt](https://github.com/guido-s/meta/files/2619269/forest14.txt)

Best wishes, Guido

**Comment by guido-s** [comment]
I would do this the following way:

1. Add a column with the (already formated) information to the dataset
2. In forest.meta(), use argument 'leftcols' to add new columns to the forest plot (and argument 'leftlabs' to provide a label.

Please have a look at the R code for an example: [forest14.txt](https://github.com/guido-s/meta/files/2619269/forest14.txt)

Best wishes, Guido
