### ISSUE TITLE
forest plots using knitr are split apart   

### ISSUE THREAD

**Issue by eotp** [guido-s/meta#9]
I am using the `forest` function from within the `gemtc` package. Further I use the `knitr` package to render the forest plots into a html report. 

The network is quite large (>40 treatments) and hence the forrest plots are considerable large too. For reasons I cannot figure out, the html report cuts each forest plot after 19 comparisons and starts with a new plot below. I am not even sure if this issues is related to the `meta` package or if it is related to some `knitr` options I am not aware of.

Any advise is highly appreciated.

**Comment by guido-s** [comment]
AFAIK, R package **gemtc** only uses metagen() from **meta** internally. Therefore, I do not think that your problem with the forest command originates from **meta**.
